### ISSUE TITLE
Onboarding To-Do list

### ISSUE THREAD

**Issue by vv-monsalve** [smc/manjari#10]
This would be the TO DO list for the onboarding process for Manjari.

- [x] Solve the Vertical Metrics [regression](https://github.com/smc/manjari/issues/4)
- [x] Solve the [remaining Fails](https://github.com/smc/manjari/issues/8)
- [x] Inspect the [Warns](https://github.com/smc/manjari/issues/9) and ensure the reported is ok in Manjari. Particularly the ones about GDEF table.
- [ ] Review Outline Quality Checklist and ensure everything is ok for Manjari. Some of the reported Warns are related to it.
- [x] Review/adjust [diacritics alignment](https://github.com/smc/manjari/issues/11)
- [x] Inspect the Diffenator reports and ensure everything is as expected.

**Comment by vv-monsalve** [comment]
> * Inspect the [Warns](https://github.com/smc/manjari/issues/9) and ensure the reported is ok in Manjari. Particularly the ones about GDEF table.

Please review the new [complete FB report](https://github.com/smc/manjari/issues/13#issuecomment-780090545) with the latest reported WARNS

**Comment by vv-monsalve** [comment]
> * Inspect the Diffenator reports and ensure everything is as expected.

Latest report in Issue [#16](https://github.com/smc/manjari/issues/16)
